{
 "title": "Ingress Status",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "targets",
    "query": "label_values(probe_success, instance)"
   }
  ]
 },
 "panels": [
  { "title": "$targets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "targets" },
  {
   "title": "$targets",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "Http Status code",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_status_code{instance=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "Uptime [30d]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(avg_over_time(probe_success{instance=~\"$targets\"}[30d]))"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "probe_success{instance=~\"$targets\"} == bool 1",
     "legendFormat": "GREEN"
    },
    {
     "expr": "probe_success{instance=~\"$targets\"} == bool 0",
     "legendFormat": "RED"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "graph",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"$targets\"}",
     "legendFormat": "seconds"
    }
   ]
  }
 ]
}