{
 "title": "Docker Registry",
 "tags": [
  "docker",
  "registry",
  "internals"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "query_result(up{kubernetes_name=\"registry\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "General Counters, CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Start Time",
   "type": "singlestat",
   "description": "start time of the process",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "dateTimeFromNow",
   "valueName": "avg",
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"docker-registry\"} * 1000"
    }
   ]
  },
  {
   "title": "Total Cache Requests",
   "type": "singlestat",
   "description": "The number of cache request received",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 1 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "expr": "registry_storage_cache_total{job=\"docker-registry\",type=\"Request\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Total Hit Cache Requests",
   "type": "singlestat",
   "description": "The number of cache request received (hits)",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 1 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "expr": "registry_storage_cache_total{job=\"docker-registry\",type=\"Hit\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Total Missed Cache Requests",
   "type": "singlestat",
   "description": "The number of cache request received (miss)",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "registry_storage_cache_total{job=\"docker-registry\",type=\"Miss\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Resident Memory Usage",
   "type": "singlestat",
   "description": "Process Resident Memory Usage",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(process_resident_memory_bytes{job=\"docker-registry\"})"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{job=\"docker-registry\"}[5m]))",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "graph",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{job=\"docker-registry\"}[5m]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes{job=\"docker-registry\"}[5m]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=\"docker-registry\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  { "title": "Registry Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "HTTP Requests",
   "type": "graph",
   "description": "The HTTP requests",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(rate(registry_http_requests_total{job=\"docker-registry\"}[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "In-Flight HTTP Requests",
   "type": "graph",
   "description": "The in-flight HTTP requests",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "registry_http_in_flight_requests{job=\"docker-registry\"}",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Registry Cache Requests Rate",
   "type": "graph",
   "description": "The rate of registry cache requests",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(rate(registry_storage_cache_total{job=\"docker-registry\"}[5m]))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Registry Action Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(registry_storage_action_seconds_sum{job=\"docker-registry\"}[2m]) * 1000",
     "legendFormat": "{{ action }}"
    }
   ]
  },
  {
   "title": "HTTP Request Latencies in seconds (blob)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{handler=\"blob\"}[10m])"
    }
   ]
  },
  {
   "title": "Upload HTTP Request Latencies in seconds (base)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{handler=\"base\"}[10m])"
    }
   ]
  },
  {
   "title": "Upload HTTP Request Latencies in seconds (blob_upload)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{handler=\"blob_upload\"}[10m])"
    }
   ]
  },
  {
   "title": "Manifest HTTP Request Latencies in seconds (manifest)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{handler=\"manifest\"}[10m])"
    }
   ]
  },
  {
   "title": "Catalog HTTP Request Latencies in seconds (catalog)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{handler=\"catalog\"}[10m])"
    }
   ]
  }
 ]
}