{
 "title": "Energy Usage",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Live", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Wattage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "esphome_sensor_value{id=\"aircon_power\"}"
    }
   ]
  },
  {
   "title": "Ampers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "amph" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "esphome_sensor_value{id=\"aircon_current\"}"
    }
   ]
  },
  { "title": "Billed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Wattage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum_over_time(esphome_sensor_value{id=\"aircon_power\"}[1h])/count_over_time(esphome_sensor_value{id=\"aircon_power\"}[1h])"
    }
   ]
  },
  {
   "title": "Ampers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "amph" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum_over_time(esphome_sensor_value{id=\"aircon_current\"}[1h])/count_over_time(esphome_sensor_value{id=\"aircon_current\"}[1h])"
    }
   ]
  },
  { "title": "Time series", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Charge",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "yaxes": [
    { "format": "currencyGBP" }
   ],
   "targets": [
    {
     "expr": "((sum_over_time(esphome_sensor_value{id=\"aircon_power\"}[1m])/1000) * 0.1893)/60",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Usage Watts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "esphome_sensor_value{id=\"aircon_power\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Supply Voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "esphome_sensor_value{id=\"aircon_voltage\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Supply Current",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "expr": "esphome_sensor_value{id=\"aircon_current\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}