{
 "title": "Firewall",
 "description": "A Grafana dashboard built to monitor pfSense that relies on influx and Telegraf.  All artifacts and instructions are maintained in github at https://github.com/VictorRobellini/pfSense-Dashboard",
 "tags": [
  "pfsense",
  "pfblocker"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   { "name": "dataSource", "query": "influxdb" },
   {
    "name": "Host",
    "label": "pfSense",
    "query": "SHOW TAG VALUES FROM \"pf\" WITH KEY = \"host\""
   },
   {
    "name": "Disk",
    "query": "SHOW TAG VALUES FROM \"diskio\" WITH KEY = \"name\" WHERE \"host\" =~ /^$Host$/"
   },
   {
    "name": "Gateway",
    "query": "SHOW TAG VALUES FROM \"gateways\" WITH KEY = \"gateway_name\" WHERE \"host\" =~ /^$Host$/ "
   },
   { "name": "WAN", "query": "igb0" },
   {
    "name": "LAN_Interfaces",
    "query": "SHOW TAG VALUES FROM \"net\" WITH KEY = \"interface\" WHERE \"host\" =~ /^$Host$/ "
   },
   {
    "name": "CPU",
    "query": "SHOW TAG VALUES FROM \"cpu\" WITH KEY = \"cpu\" WHERE \"host\" =~ /^$Host$/ and cpu !~ /cpu-total/"
   },
   {
    "name": "Interfaces",
    "query": "SHOW TAG VALUES FROM \"interface\" WITH KEY = \"name\" WHERE \"host\" =~ /^$Host$/ "
   },
   {
    "name": "Sensor",
    "query": "SHOW TAG VALUES FROM \"temperature\" WITH KEY = \"sensor\" WHERE \"host\" =~ /^$Host$/"
   }
  ]
 },
 "panels": [
  { "title": "Hardware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Users",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "system",
     "query": "SELECT \"n_users\" FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "n_users" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Total",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "CPU Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cpu" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "cpu", "operator": "=~", "value": "/^$CPU$/" }
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "Load 15m",
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime_format" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "disk",
     "query": "SELECT \"used_percent\" FROM \"disk\" WHERE (\"host\" =~ /^$Host$/ AND \"path\" = '/var/run' AND \"device\" =~ /^$Disk$/) AND $timeFilter GROUP BY \"device\"",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/var/run" }
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Ram",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Ram",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Ram",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature Sensors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "degrees" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "sensor", "operator": "=~", "value": "/^$Sensor$/" }
     ]
    }
   ]
  },
  { "title": "Systems", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Blocked by country",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 14 },
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(pfsense_blocked_total) by (city, longitude, latitude)"
    }
   ]
  },
  {
   "title": "Blocked by protocol",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pfsense_blocked_total) by (protocol)",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Gateway RTT - $Gateway ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 14 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "alias": "$tag_gateway_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "gateway_name" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "gateways",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "gateway_name", "operator": "=~", "value": "/^$Gateway$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface summary",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "interface",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Status" ], "type": "alias" }
      ],
      [
       { "params": [ "friendlyname" ], "type": "field" },
       { "params": [ "pfSense Label" ], "type": "alias" }
      ],
      [
       { "params": [ "ip_address" ], "type": "field" },
       { "params": [ "IP Address" ], "type": "alias" }
      ],
      [
       { "params": [ "mac_address" ], "type": "field" },
       { "params": [ "Physical Address" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "WAN Traffic - $WAN",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "WAN Traffic Recv",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT derivative(mean(\"bytes_recv\"), 1s)  *-1 FROM \"autogen\".\"net\" WHERE (\"host\" = 'pfSense-home-master.home' AND \"interface\" = 'vtnet0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$WAN$/" }
     ]
    },
    {
     "alias": "WAN Traffic Sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT derivative(mean(\"bytes_sent\"), 1s) FROM \"net\" WHERE (\"host\" =~ /^$Host$/ AND \"interface\" =~ /^$WAN$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$WAN$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN Throughput - $WAN",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Drop In",
     "measurement": "net",
     "query": "SELECT mean(\"drop_in\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$Interface$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "Drop Out",
     "measurement": "net",
     "query": "SELECT mean(\"drop_out\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "drop_out" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$Interface$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "Err In",
     "measurement": "net",
     "query": "SELECT mean(\"err_in\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "err_in" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$Interface$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "Err Out",
     "measurement": "net",
     "query": "SELECT mean(\"err_out\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "err_out" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$Interface$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "Pckts Recv",
     "measurement": "net",
     "query": "SELECT mean(\"packets_recv\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "packets_recv" ], "type": "field" },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "Pckts Sent",
     "measurement": "net",
     "query": "SELECT mean(\"packets_sent\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "packets_sent" ], "type": "field" },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  { "title": "Lan Interfaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "LAN Traffic - $LAN_Interfaces",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "repeat": "LAN_Interfaces",
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_interface - LAN Traffic Recv",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT derivative(mean(\"bytes_recv\"), 1s)  *-1 FROM \"autogen\".\"net\" WHERE (\"host\" = 'pfSense-home-master.home' AND \"interface\" = 'vtnet0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" }
     ]
    },
    {
     "alias": "$tag_interface - LAN Traffic Sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT derivative(mean(\"bytes_sent\"), 1s) FROM \"net\" WHERE (\"host\" = 'pfSense-home-master.home' AND \"interface\" = 'vtnet0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN Throughput - $LAN_Interfaces",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "repeat": "LAN_Interfaces",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_interface - Drop In",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"drop_in\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Drop Out",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"drop_out\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "drop_out" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Err In",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"err_in\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "err_in" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Err Out",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"err_out\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "err_out" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Pckts Recv",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"packets_recv\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "packets_recv" ], "type": "field" },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Pckts Sent",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"packets_sent\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "packets_sent" ], "type": "field" },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN Traffic - $LAN_Interfaces",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_interface - LAN Traffic Recv",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT derivative(mean(\"bytes_recv\"), 1s)  *-1 FROM \"autogen\".\"net\" WHERE (\"host\" = 'pfSense-home-master.home' AND \"interface\" = 'vtnet0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" }
     ]
    },
    {
     "alias": "$tag_interface - LAN Traffic Sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT derivative(mean(\"bytes_sent\"), 1s) FROM \"net\" WHERE (\"host\" = 'pfSense-home-master.home' AND \"interface\" = 'vtnet0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN Throughput - $LAN_Interfaces",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_interface - Drop In",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"drop_in\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Drop Out",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"drop_out\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "drop_out" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Err In",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"err_in\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "err_in" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Err Out",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"err_out\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "err_out" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Pckts Recv",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"packets_recv\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "packets_recv" ], "type": "field" },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Pckts Sent",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"packets_sent\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "packets_sent" ], "type": "field" },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN Traffic - $LAN_Interfaces",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_interface - LAN Traffic Recv",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT derivative(mean(\"bytes_recv\"), 1s)  *-1 FROM \"autogen\".\"net\" WHERE (\"host\" = 'pfSense-home-master.home' AND \"interface\" = 'vtnet0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" }
     ]
    },
    {
     "alias": "$tag_interface - LAN Traffic Sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT derivative(mean(\"bytes_sent\"), 1s) FROM \"net\" WHERE (\"host\" = 'pfSense-home-master.home' AND \"interface\" = 'vtnet0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN Throughput - $LAN_Interfaces",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_interface - Drop In",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"drop_in\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Drop Out",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"drop_out\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "drop_out" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Err In",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"err_in\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "err_in" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Err Out",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"err_out\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "err_out" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Pckts Recv",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"packets_recv\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "packets_recv" ], "type": "field" },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Pckts Sent",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"packets_sent\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "packets_sent" ], "type": "field" },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN Traffic - $LAN_Interfaces",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_interface - LAN Traffic Recv",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT derivative(mean(\"bytes_recv\"), 1s)  *-1 FROM \"autogen\".\"net\" WHERE (\"host\" = 'pfSense-home-master.home' AND \"interface\" = 'vtnet0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" }
     ]
    },
    {
     "alias": "$tag_interface - LAN Traffic Sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT derivative(mean(\"bytes_sent\"), 1s) FROM \"net\" WHERE (\"host\" = 'pfSense-home-master.home' AND \"interface\" = 'vtnet0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN Throughput - $LAN_Interfaces",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_interface - Drop In",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"drop_in\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Drop Out",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"drop_out\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "drop_out" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Err In",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"err_in\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "err_in" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Err Out",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"err_out\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "err_out" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Pckts Recv",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"packets_recv\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "packets_recv" ], "type": "field" },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Pckts Sent",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"packets_sent\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "packets_sent" ], "type": "field" },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN Traffic - $LAN_Interfaces",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_interface - LAN Traffic Recv",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT derivative(mean(\"bytes_recv\"), 1s)  *-1 FROM \"autogen\".\"net\" WHERE (\"host\" = 'pfSense-home-master.home' AND \"interface\" = 'vtnet0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" }
     ]
    },
    {
     "alias": "$tag_interface - LAN Traffic Sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT derivative(mean(\"bytes_sent\"), 1s) FROM \"net\" WHERE (\"host\" = 'pfSense-home-master.home' AND \"interface\" = 'vtnet0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN Throughput - $LAN_Interfaces",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_interface - Drop In",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"drop_in\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Drop Out",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"drop_out\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "drop_out" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Err In",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"err_in\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "err_in" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Err Out",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"err_out\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "err_out" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Pckts Recv",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"packets_recv\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "packets_recv" ], "type": "field" },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Pckts Sent",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"packets_sent\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "packets_sent" ], "type": "field" },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN Traffic - $LAN_Interfaces",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_interface - LAN Traffic Recv",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT derivative(mean(\"bytes_recv\"), 1s)  *-1 FROM \"autogen\".\"net\" WHERE (\"host\" = 'pfSense-home-master.home' AND \"interface\" = 'vtnet0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" }
     ]
    },
    {
     "alias": "$tag_interface - LAN Traffic Sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT derivative(mean(\"bytes_sent\"), 1s) FROM \"net\" WHERE (\"host\" = 'pfSense-home-master.home' AND \"interface\" = 'vtnet0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN Throughput - $LAN_Interfaces",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_interface - Drop In",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"drop_in\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Drop Out",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"drop_out\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "drop_out" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Err In",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"err_in\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "err_in" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Err Out",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"err_out\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "err_out" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Pckts Recv",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"packets_recv\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "packets_recv" ], "type": "field" },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Pckts Sent",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"packets_sent\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "packets_sent" ], "type": "field" },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN Traffic - $LAN_Interfaces",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_interface - LAN Traffic Recv",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT derivative(mean(\"bytes_recv\"), 1s)  *-1 FROM \"autogen\".\"net\" WHERE (\"host\" = 'pfSense-home-master.home' AND \"interface\" = 'vtnet0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" }
     ]
    },
    {
     "alias": "$tag_interface - LAN Traffic Sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT derivative(mean(\"bytes_sent\"), 1s) FROM \"net\" WHERE (\"host\" = 'pfSense-home-master.home' AND \"interface\" = 'vtnet0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN Throughput - $LAN_Interfaces",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_interface - Drop In",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"drop_in\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Drop Out",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"drop_out\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "drop_out" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Err In",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"err_in\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "err_in" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Err Out",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"err_out\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "err_out" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Pckts Recv",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"packets_recv\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "packets_recv" ], "type": "field" },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Pckts Sent",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"packets_sent\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "packets_sent" ], "type": "field" },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN Traffic - $LAN_Interfaces",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_interface - LAN Traffic Recv",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT derivative(mean(\"bytes_recv\"), 1s)  *-1 FROM \"autogen\".\"net\" WHERE (\"host\" = 'pfSense-home-master.home' AND \"interface\" = 'vtnet0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" }
     ]
    },
    {
     "alias": "$tag_interface - LAN Traffic Sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT derivative(mean(\"bytes_sent\"), 1s) FROM \"net\" WHERE (\"host\" = 'pfSense-home-master.home' AND \"interface\" = 'vtnet0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN Throughput - $LAN_Interfaces",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_interface - Drop In",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"drop_in\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Drop Out",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"drop_out\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "drop_out" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Err In",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"err_in\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "err_in" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Err Out",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"err_out\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "err_out" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Pckts Recv",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"packets_recv\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "packets_recv" ], "type": "field" },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Pckts Sent",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"packets_sent\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "packets_sent" ], "type": "field" },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN Traffic - $LAN_Interfaces",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_interface - LAN Traffic Recv",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT derivative(mean(\"bytes_recv\"), 1s)  *-1 FROM \"autogen\".\"net\" WHERE (\"host\" = 'pfSense-home-master.home' AND \"interface\" = 'vtnet0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" }
     ]
    },
    {
     "alias": "$tag_interface - LAN Traffic Sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT derivative(mean(\"bytes_sent\"), 1s) FROM \"net\" WHERE (\"host\" = 'pfSense-home-master.home' AND \"interface\" = 'vtnet0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN Throughput - $LAN_Interfaces",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_interface - Drop In",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"drop_in\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Drop Out",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"drop_out\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "drop_out" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Err In",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"err_in\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "err_in" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Err Out",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"err_out\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "err_out" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Pckts Recv",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"packets_recv\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "packets_recv" ], "type": "field" },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Pckts Sent",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"packets_sent\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "packets_sent" ], "type": "field" },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN Traffic - $LAN_Interfaces",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_interface - LAN Traffic Recv",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT derivative(mean(\"bytes_recv\"), 1s)  *-1 FROM \"autogen\".\"net\" WHERE (\"host\" = 'pfSense-home-master.home' AND \"interface\" = 'vtnet0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" }
     ]
    },
    {
     "alias": "$tag_interface - LAN Traffic Sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT derivative(mean(\"bytes_sent\"), 1s) FROM \"net\" WHERE (\"host\" = 'pfSense-home-master.home' AND \"interface\" = 'vtnet0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN Throughput - $LAN_Interfaces",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_interface - Drop In",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"drop_in\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Drop Out",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"drop_out\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "drop_out" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Err In",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"err_in\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "err_in" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Err Out",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"err_out\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "err_out" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Pckts Recv",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"packets_recv\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "packets_recv" ], "type": "field" },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - Pckts Sent",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"packets_sent\") FROM \"net\" WHERE (\"interface\" =~ /^$Interface$/ AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "packets_sent" ], "type": "field" },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  }
 ]
}