{
 "title": "Minecraft",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(mc_tps{}, kubernetes_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Ticks Per Second",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mc_tps{kubernetes_name=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Chunks Rendered",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mc_loaded_chunks_total{kubernetes_name=\"$instance\"}",
     "legendFormat": "{{world}}"
    }
   ]
  },
  { "title": "World Map", "type": "innius-video-panel", "gridPos": { "h": 12, "w": 9, "x": 15, "y": 0 } },
  {
   "title": "Players Per World",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mc_players_online_total{kubernetes_name=\"$instance\"}",
     "legendFormat": "{{world}}"
    }
   ]
  },
  {
   "title": "Tick rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_tps{kubernetes_name=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Entities",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mc_entities_total{kubernetes_name=\"$instance\"}) by (world)",
     "legendFormat": "{{world}}"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_jvm_memory{kubernetes_name=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}