{
 "title": "Plex",
 "description": "Plex Stats",
 "tags": [
  "Varken",
  "Plex",
  "Tautulli",
  "Sonarr",
  "Radarr",
  "Sickchill"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "movieslibrary", "label": "Movies Library Name", "query": "Films" },
   { "name": "movies4klibrary", "label": "4K Movies Library Name", "query": "Movies 4K" },
   { "name": "tvlibrary", "label": "TV Library Name", "query": "TV Shows" },
   { "name": "tv4klibrary", "label": "TV 4K Library Name", "query": "TV Shows 4K" },
   { "name": "ombiurl", "label": "Ombi URL", "query": "https://ombi.bilbercode.com" },
   {
    "name": "tautulliurl",
    "label": "Tautulli URL",
    "query": "https://tautulli.bilbercode.com"
   },
   { "name": "sonarrurl", "label": "Sonarr URL", "query": "https://sonarr.bilbercode.com" },
   { "name": "radarrurl", "label": "Radarr URL", "query": "https://radarr.bilbercode.com" },
   {
    "name": "sickchillurl",
    "label": "Sickchill URL",
    "query": "https://sickchill.bilbercode.com"
   }
  ]
 },
 "panels": [
  {
   "title": "Total BW",
   "type": "singlestat",
   "description": "Streaming Brain Estimate",
   "gridPos": { "h": 2, "w": 2, "x": 1, "y": 0 },
   "format": "Kbits",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total_bandwidth" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "LAN BW",
   "type": "singlestat",
   "description": "Streaming Brain Estimate",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 0 },
   "format": "Kbits",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "lan_bandwidth" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "WAN BW",
   "type": "singlestat",
   "description": "Streaming Brain Estimate",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 0 },
   "format": "Kbits",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "wan_bandwidth" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "Req. Pending",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Ombi",
     "select": [
      [
       { "params": [ "pending" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Request_Counts" }
     ]
    }
   ]
  },
  {
   "title": "Requests Approved",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Ombi",
     "select": [
      [
       { "params": [ "approved" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Request_Counts" }
     ]
    }
   ]
  },
  {
   "title": "Requests Completed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Ombi",
     "select": [
      [
       { "params": [ "available" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Request_Counts" }
     ]
    }
   ]
  },
  {
   "title": "Recently Added Movies",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "diff",
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$movieslibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "Movies",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$movieslibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "TV Shows",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$tvlibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "TV Seasons",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "seasons" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$tvlibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "TV Episodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "episodes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$tvlibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Streams",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "stream_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "Transocde Streams",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "transcode_streams" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "Direct Play Streams",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "direct_play_streams" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "Direct Stream",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "direct_streams" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "Issues Pending",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Ombi",
     "select": [
      [
       { "params": [ "pending" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Issues_Counts" }
     ]
    }
   ]
  },
  {
   "title": "Issues Resolved",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Ombi",
     "select": [
      [
       { "params": [ "resolved" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Issues_Counts" }
     ]
    }
   ]
  },
  {
   "title": "Issues In Progress",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Ombi",
     "select": [
      [
       { "params": [ "in_progress" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Issues_Counts" }
     ]
    }
   ]
  },
  {
   "title": "Recently Added TV",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 2 },
   "format": "none",
   "valueName": "diff",
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "episodes" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$tvlibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "4K Movies",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$movies4klibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "4K TV Shows",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$tv4klibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "4K TV Seasons",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "seasons" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$tv4klibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "4K TV Episodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "episodes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$tv4klibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "Device Types",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_device_type",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "device_type" ], "type": "tag" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "Tautulli",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ],
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Stream Types",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_video_decision",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "video_decision" ], "type": "tag" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "Tautulli",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ],
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Movies in Queue",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "protocol_id" ], "type": "tag" },
      { "params": [ "quality" ], "type": "tag" }
     ],
     "measurement": "Radarr",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Queue" }
     ]
    }
   ]
  },
  {
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 4 },
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_region_code",
     "groupBy": [
      { "params": [ "latitude" ], "type": "tag" },
      { "params": [ "longitude" ], "type": "tag" },
      { "params": [ "full_location" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "metric" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ]
    }
   ]
  },
  {
   "title": "TV Shows in Queue",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "protocol_id" ], "type": "tag" },
      { "params": [ "sxe" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "Sonarr",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Queue" }
     ]
    }
   ]
  },
  {
   "title": "Server Popularity",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 12 },
   "targets": [
    {
     "alias": ".",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "Tautulli",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "TV Shows on Today (Sonarr)",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "downloaded" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "sxe" ], "type": "tag" }
     ],
     "measurement": "Sonarr",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Future" }
     ]
    }
   ]
  },
  {
   "title": "Users Online",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "title" ], "type": "tag" },
      { "params": [ "quality" ], "type": "tag" },
      { "params": [ "video_decision" ], "type": "tag" },
      { "params": [ "quality_profile" ], "type": "tag" },
      { "params": [ "platform" ], "type": "tag" },
      { "params": [ "product_version" ], "type": "tag" },
      { "params": [ "location" ], "type": "tag" }
     ],
     "measurement": "Tautulli",
     "query": "SELECT distinct(\"hash\") FROM \"Tautulli\" WHERE (\"type\" = 'Session') AND $timeFilter GROUP BY \"friendly_name\",  \"title\", \"quality\", \"video_decision\", \"quality_profile\", \"platform\", \"product_version\", \"location\", \"player_state\"",
     "select": [
      [
       { "params": [ "session_key" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ]
    }
   ]
  },
  {
   "title": "TV Shows (Sickchill)",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "sxe" ], "type": "tag" },
      { "params": [ "airdate" ], "type": "tag" }
     ],
     "measurement": "SickChill",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Missing Available Movies",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 23 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "titleSlug" ], "type": "tag" }
     ],
     "measurement": "Radarr",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "Missing_Available", "operator": "=", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Ombi Requests Pending",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "title" ], "type": "tag" },
      { "params": [ "requested_date" ], "type": "tag" },
      { "params": [ "requested_user" ], "type": "tag" },
      { "params": [ "request_type" ], "type": "tag" },
      { "params": [ "status" ], "type": "tag" }
     ],
     "measurement": "Ombi",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Requests" },
      { "condition": "AND", "key": "status", "operator": "!=", "value": "0" },
      { "condition": "AND", "key": "status", "operator": "!=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "Missing TV Shows (Last 7 Days)",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "sxe" ], "type": "tag" },
      { "params": [ "server" ], "type": "tag" }
     ],
     "measurement": "Sonarr",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Missing" }
     ]
    }
   ]
  }
 ]
}